// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthenticationSchema from "@/models/drizzle/authentication.model";
import * as DataRoomSchema from "@/models/drizzle/dataRoom.model";
import * as DividendSchema from "@/models/drizzle/dividend.model";
import * as GlobalSchema from "@/models/drizzle/global.model";
import * as MediaSchema from "@/models/drizzle/media.model";
import * as OrderSchema from "@/models/drizzle/order.model";
import * as PaymentSchema from "@/models/drizzle/payment.model";
import * as PaypalSchema from "@/models/drizzle/paypal.model";
import * as PlaidSchema from "@/models/drizzle/plaid.model";
import * as PortfolioSchema from "@/models/drizzle/portfolio.model";
import * as WalletSchema from "@/models/drizzle/wallet.model";

const schema = {
	...AuthenticationSchema,
	...DataRoomSchema,
	...DividendSchema,
	...GlobalSchema,
	...MediaSchema,
	...OrderSchema,
	...PaymentSchema,
	...PaypalSchema,
	...PlaidSchema,
	...PortfolioSchema,
	...WalletSchema
};

export default schema;
